### ISSUE TITLE
pybind11_catkin target compilation for different python versions?

### ISSUE THREAD

**Issue by astridpetitjean** [ipab-slmc/pybind11_catkin#14]
Hello, 

I am unsure of how I would go about to compile my catkin package in order to be used with varying python versions? 
I tried to set the PYBIND11_PYTHON_VERSION flag, but it did not do the work.

**Comment by wxmerkt** [comment]
Hi @astridpetitjean,
Which version are you using? E.g. which git commit or whether from binaries along with the ROS distro? Could you share an example CMakeLists file?

**Comment by astridpetitjean** [comment]
Sorry for my incomplete question, it actually relates to an issue I had when compiling the examples from the pybind11_examples repo, which I describe here: https://github.com/arturmiller/pybind11_examples/issues/1. 

I am on Ubuntu18.04, ROS Melodic. I followed the instructions given by https://github.com/arturmiller/pybind11_examples/, namely: 
``` 
sudo apt-get install ros-melodic-pybind11-catkin
``` 
According to the package.xml of the installed pybind11_catkin package, I am using version: 2.4.3.

As I mention in the issue I opened in the pybind11_examples, I do have different python versions installed on my machine (python 2.7, 3.6 and since recently also 3.7). 


1. **Python 2.7:** with a slight modification of the CMakeLists.txt of cpp_object_attr, I am able to compile and generate cpp_example module that is available for python 2.7: 

```
cmake_minimum_required(VERSION 3.0.2)
project(cpp_object_attr)

find_package(PythonLibs 2.7 REQUIRED) # here I require to be set to 2.7

find_package(catkin REQUIRED COMPONENTS
    pybind11_catkin)

catkin_python_setup()

catkin_package(
    LIBRARIES
    CATKIN_DEPENDS pybind11_catkin
)

include_directories(${PYTHON_INCLUDE_DIRS} ${catkin_INCLUDE_DIRS})

pybind_add_module(cpp_object MODULE src/cpp_object.cpp)
pybind_add_module(example SHARED src/example.cpp )
add_executable(main src/main.cpp)
target_link_libraries(main ${PYTHON_LIBRARIES} example)

install(TARGETS main
                cpp_object
  LIBRARY DESTINATION ${PYTHON_INSTALL_DIR}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)
```

2. **Python 3.6**: In this case I simply changed my catkin config to use python 3.6 instead of 2.7, adapting the version requested for PythonLibs in my CMakeLists.txt. 
```
catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
```
This works fine and I am able to find the module in python3.6. 

3. **Python 3.7**: This is when things become trickier and I did not manage to generate a module that is available for python3.7. I tried several things: 
* Same as method (2) setting python executable to the python3.7 paths, however as this sets the python version for the whole project, I run into missing package which I actually have installed. I am not sure if this would be the right way to go (?).    
```
ImportError: "from catkin_pkg.package import parse_package" failed: No module named 'catkin_pkg'
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
``` 
* Inspired by the macro of pybind11_catkin I did set manually the flags for pybind11 to the python version 3.7, something like this, just before calling pybind11_add_module (pybind11 command, not pybind11_catkin macro): 
``` 
set(PYBIND11_PYTHON_VERSION 3.7.7)
set(PYTHON_EXECUTABLE /home/astrid/sandbox_015/bin/python3)
set(PYTHON_INCLUDE_DIRS /home/astrid/sandbox_015/include/python3.7m)
set(PYTHON_LIBRARIES /home/astrid/sandbox_015/lib/libpython3.7m.so)
pybind11_add_module(my_module MODULE ${MY_SOURCES})
```
This compiled, but when I tried to load my_module from within a python3.7 session, I got an saying I had an undefined reference to a symbol called something like _Py... . To my understanding this is a typical error when there are different python versions involved, and I am suspecting that somewhere I am mixing python versions or that I am not using pybind11 correctly. 

I am quite new to all this, and don't really know what direction I should be searching. I would like to compile my catkin package containing pybind11 code to be able to interface my library (other custom catkin packages, c++) to work with different versions of python (including python 3.7). 

Thank you for your help :)

**Comment by wxmerkt** [comment]
Hi @astridpetitjean,
Thank you very much for the details - so based on your description, it works fine with the stock Python versions shipped with 18.04 - 2.7 and 3.6.

Did you install and activate 3.7 as a virtualenv? It seems to be some default paths are not set up proper and it might pick up 3.6. You can get more information when building using the `-i` option i.e. `catkin build -i`.
You could install the missing packages with `python3.7 -m pip install --user catkin-pkg` etc. - but that might cause other issues (overlaying of tools in your local folder!)

Hope this helps

**Comment by astridpetitjean** [comment]
Hello @wxmerkt, 
Thank you for your answer. It looks indeed like some of the defaults path were not set up properly. At some point during the debugging process I "broke" my installation and re-installed ROS, which solved the problem... 

I can now successfully compile for Python 3.7 by setting the three python environment variables to the respective paths: 
```  
catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3.7 -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so
```

Thank you very much.

**Comment by wxmerkt** [comment]
Awesome, happy to hear it's resolved! I'll close the issue then and hope this package is useful for your work :-)
