### ISSUE TITLE
pybind11 version

### ISSUE THREAD

**Issue by ags-dy** [ipab-slmc/pybind11_catkin#15]
Hi,

I see that the latest commit updates pybind11_catkin to track pybind11 2.6.0:
https://github.com/ipab-slmc/pybind11_catkin/commit/b749719a044f56983f88049e8758c5ef5700651c

but when I print the version in cmake:
```message(${pybind11_catkin_VERSION})```
it return 2.5.0

Is this just because the version has not been updated in some cmake file, or is it really still 2.5.0?

(Also pybind11 have released 2.6.1 which fix some regressions in 2.6.0)

Thanks,
Austin

**Comment by wxmerkt** [comment]
Hi Austin, did you install from binaries? I believe we did not update the binary release to the ROS buildfarm

**Comment by ags-dy** [comment]
I was originally on the binaries from:
```sudo apt install ros-melodic-pybind11-catkin```
which returns version 2.4.3

but now I have cloned this repo and built from master which in theory should be 2.6.0 but cmake says 2.5.0.

**Comment by wxmerkt** [comment]
My bad - I forgot to update the `version` tag in the package.xml. So, it's whichever version is cloned (so 2.6.0) - I just fixed it

**Comment by wxmerkt** [comment]
I am happy to update to 2.6.1 if you can confirm that it works as intended?

**Comment by ags-dy** [comment]
I will try 2.6.1 now and see if that works.

**Comment by ags-dy** [comment]
I have change the url to download the 2.6.1.zip and everything appears to work...  This is not the most robust of test cases, but given its a minor version its probably fine.

I'd also just like to thank for you for making pybind11 work in catkin, its been incredibly useful to me :+1:

**Comment by wxmerkt** [comment]
Thanks for the feedback, I'll test it here locally as well and will then update the repository.
