### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by alexMarFar** [ipab-slmc/pybind11_catkin#20]
Hi! I'm migrating a project that works with ROS2 Foxy from ROS1 Noetic and it depends on this package. 

I wanted to verify if there is a ROS2 Foxy compatibility or if I can work directly with pybind11.

Thank you in advance,

**Comment by wxmerkt** [comment]
Hi @alexMarFar 
pybind11 is directly vendored for ROS2, so you should be able to use `pybind11_vendor`. We are not planning on releasing this package for ROS2.

**Comment by alexMarFar** [comment]
Oh, okay! Thank you so much!
