### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by safijari** [ipab-slmc/pybind11_catkin#3]
Do you have an example project you could share? I have a C++ library wrapped using pybind 11 for which I have a setup.py file that builds it correctly. Would like to figure out how to get it working with catkin.

**Comment by wxmerkt** [comment]
Hi @safijari.
We are mainly using it in the open source [``exotica_python``](https://github.com/ipab-slmc/exotica/tree/master/exotica_python) bindings. Have a look at the [``CMakeLists.txt``](https://github.com/ipab-slmc/exotica/blob/master/exotica_python/CMakeLists.txt) and the [source file](https://github.com/ipab-slmc/exotica/blob/master/exotica_python/src/Exotica.cpp). If you have any questions please let us know.

cc: @VladimirIvan

**Comment by safijari** [comment]
Fantastic. That looks really straight forward to use. God I'm loving this library :)

**Comment by arturmiller** [comment]
Hello, I wrote a few examples [here](https://github.com/arturmiller/pybind11_examples). Maybe someone finds them useful. :)

**Comment by wxmerkt** [comment]
Very cool @arturmiller! Do you mind making a PR to add it to the README? Or PR the examples to this repository?
We are currently binary released for Kinetic and aim to do so for Melodic in the near future.

**Comment by arturmiller** [comment]
Yes I would like to contribute, but I'm not sure if it is better to add the examples to this repository or to just link them here. If I I would put these examples here, should I create an "examples" folder, or how to do it best?

**Comment by wxmerkt** [comment]
I think a link in the README is fine :)
