### ISSUE TITLE
Bleeding edge, or released version?

### ISSUE THREAD

**Issue by gavanderhoorn** [ipab-slmc/pybind11_catkin#9]
The readme status:

> This repository wraps the bleeding edge versions of `pybind11` for use in catkin-based projects.

But `CMakeLists.txt` appears to actually [package version 2.2.4](https://github.com/ipab-slmc/pybind11_catkin/blob/895b48fd5ec6a68337bce1206e18433cf3dbd384/CMakeLists.txt#L7-L12).

I'm actually happy it's not fetching `master` or something similar, but just for clarification: you're tracking upstream with this package, but packaging a newer version is only done if/when a human decides to fetch the newer release archive.

Correct?

**Comment by wxmerkt** [comment]
Hi @gavanderhoorn,
Yes, correct. I will amend the README. We packaged 2.2.4 as it contains the Eigen<>NumPy fixes and updates that aren't in the bionic-released debian yet. We haven't tracked newer versions yet. Would you like me to make a new release with the most recent release?

**Comment by gavanderhoorn** [comment]
> Would you like me to make a new release with the most recent release?

No, I'm fine with `2.2.4` personally. Just wanted to make sure I didn't misunderstand the readme/`CMakeLists.txt`.

**Comment by gavanderhoorn** [comment]
Thanks for clearing this up.
